version: "3.9"

services:
  application: &application
    build:
      context: ../..
      dockerfile: Docker/Prod/dockerfile.application
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./app_storage:/app/Storage
      - app_sessions:/var/lib/php/sessions
    env_file:
      - ../../.env
  server:
    image: nginx:alpine
    env_file:
      - ../../.env
    ports:
      - "${APPLICATION_PORT:-8080}:80"
    volumes:
      - ./apcu-nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - application

volumes:
  app_sessions: